version: '3.8'

services:
    php:
        container_name: php8
        build: php8
        ports:
          - "9000:8000"
        volumes:
            - ./data_center:/var/www/html

    mailer:
        image: schickling/mailcatcher
        ports: [1025, 1080]

    database:
        image: postgres:latest
        environment:
            POSTGRES_DB: data_processing
            POSTGRES_PASSWORD: karim
            POSTGRES_USER: karim
        volumes:
            - ./db_data:/var/lib/postgresql/data:rw
        ports:
            - "5432"

volumes:
  db-data:
